eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

logging:
  file: /var/log/sample-boot-application.log
spring:
  boot:
    admin:
      url: http://localhost:8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS