logging:
  file: /var/log/sample-boot-application.log
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: DEBUG
zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:8087/spring-security-oauth-server/oauth
    pc: /product/**
    # Allows to request by http://localhost:8085/product/catalog/
    po:
      # Allows to request by curl --request PUT   --url http://localhost:8085/catalog/{productRef}/order
      path: /catalog/**/order
      stripPrefix: false



spring:
  application:
    name: zuul
  boot:
    admin:
      url: http://localhost:8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  application:
    name: zuul
  cloud:
    config:
      enabled: false
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

