logging:
  file: /var/log/sample-boot-application.log
spring:
  boot:
    admin:
      url: http://localhost:8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  applicatoin:
    name: Eureka Server

server:
  port: 8000

eureka:
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  instance:
    hostname: localhost
